timing:
  listupdate: 300
  entity:
    period: 5
    payload: 200000
scanning:
  horizontalrange: 1
  verticalbelow: 2
  verticalabove: 2
librarian:
  bookproduction: 1000
butcher:
  radius: 2
  shear: 3000
